CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  usernamename VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS subreddits (
  id SERIAL PRIMARY KEY,
  name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGSERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users (id),
  subreddit_id INTEGER REFERENCES subreddits (id)
);